---
from: markdown+emoji
---

# Instalação


::: {.callout-important appearance="simple"}
Para acompanhar a oficina, você deve ter os seguintes programas instalados em sua máquina ***antes*** do dia do workshop.

- R e RStudio
- Alguns pacotes em R
- Java JDK 21

Veja as instruções abaixo:
:::

## Instalando R e RStudio

Assumimos que você já tenha o R e o RStudio instalados em sua máquina. Caso não tenha, [siga estas instruções simples aqui](https://posit.co/download/rstudio-desktop/#download).


## Instalando pacotes de R

O workshop utiliza alguns pacotes em R que precisam ser instalados em sua máquina. A maneira mais simples de fazer isso é executando o código abaixo. Isso pode levar alguns minutos se for a primeira vez que você instala esses pacotes.

```{R eval = FALSE, message = FALSE}
pkgs <- c(
  'r5r',
  'accessibility',
  'aopdata',
  'rJavaEnv',
  'ggplot2',
  'mapview',
  'quantreg',
  'dplyr',
  'h3jsr',
  'sf'
  )

install.packages(pkgs)
```


## Instalando Java

Para usar o pacote `{r5r}` (versão v2.0 ou superior), você precisará ter o *Java Development Kit (JDK) 21* instalado em seu computador. Existem diversas implementações de JDK de código aberto. A maneira mais fácil de instalar o JDK é utilizando o novo pacote [{rJavaEnv}](https://www.ekotov.pro/rJavaEnv/) no R, desenvolvido por Egor Kotov (obrigado, Egor!).

```{R eval = FALSE}
# checa se tem alguma versao do Java instalado 
rJavaEnv::java_check_version_rjava()

## se esta é a primeira vez que você usa o {rJavaEnv}, talvez seja 
## necessário executar o código abaixo para consentir a instalação do Java
rJavaEnv::rje_consent(provided = TRUE)

# instala Java 21
rJavaEnv::java_quick_install(version = 21)

# check if Java was successfully installed
rJavaEnv::java_check_version_rjava()
```

Alternativamente, você pode baixar e instalar manualmente qualquer uma dessas implementações de JDK:

- [Adoptium/Eclipse Temurin](https://adoptium.net/)
- [Amazon Corretto](https://aws.amazon.com/corretto/)
- [Oracle OpenJDK](https://jdk.java.net/21/)


Aqui estão alguns slides complementares explicando os requisitos computacionais para realizar análises de roteamento e acessibilidade de transporte com `R`.

<p><embed src="slides/2.1_computational_requirements.pdf" style="width:100.0%;height:100vh;" /></p>

